### ISSUE TITLE
telemetry can be read with IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG

### ISSUE THREAD

**Issue by tim-oleksii** [ken-yossy/nvmetool-win#6] opened 2020-09-16 16:46 UTC
Since win10 2004 

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ni-ntddstor-ioctl_storage_get_device_internal_log

https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/stornvme-feature-support

**Comment by ken-yossy** [comment] 2020-09-16 22:58
I will try it. thank you.

**Comment by ken-yossy** [comment] 2020-09-17 04:31
In [1], it says that Telemetry is available through `StorageAdapterProtocolSpecificProperty` / `StorageDeviceProtocolSpecificProperty` from `IOCTL_STORAGE_QUERY_PROPERTY`.

So I checked my code and changed to use `StorageAdapterProtocolSpecificProperty` rather than `StorageDeviceProtocolSpecificProperty` with `IOCTL_STORAGE_QUERY_PROPERTY`.

As a result, I succeeded in IoDeciveControl().

I used EXCERIA M.2 SSD by Kioxia.

Note that, this program does not support getting "Telemetry Controller/Host-Initiated Data Block"s because the SSD I'm using does not have any Controller-Initiated telemetry data and seems to be unable to create Host-Initiated telemetry data...

[1] https://docs.microsoft.com/en-us/windows-hardware/drivers/storage/stornvme-feature-support

**Comment by ken-yossy** [comment] 2020-09-17 04:48
Hi Tim,

Thank you very much for your comment.
With your comment, I found how to fix getting telemetry (header) data on Windows 10 1909.

If you are still watching this ticket, please close it if you do not mind.
Even if you do not close, I will close this ticket after a week.

Thank you
Ken

**Comment by tim-oleksii** [comment] 2020-09-17 06:25
Hi Ken,

There is a particular reason MS introduced IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG in 2004. This syscall sets `LSP` bit. However, data layout is quite different, it doesn't comply to NVME spec, but it's quite close to it.
Additionally, this one is fast - data is read with regards to MDTS.

Both approaches are feasible.

I've checked all the points with modified FW on my eSSD.

Best regards,
Alexey

**Comment by ken-yossy** [comment] 2020-09-17 06:44
Hi Alexey,

Thank you for your further information.

> There is a particular reason MS introduced IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG in 2004. This syscall sets `LSP` bit. However, data layout is quite different, it doesn't comply to NVME spec, but it's quite close to it.
> Additionally, this one is fast - data is read with regards to MDTS.

It's interesting. I'm just thinking about how to create telemetry log.

> Both approaches are feasible.
> 
> I've checked all the points with modified FW on my eSSD.

It's great. Ok, I'll try using `IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG` to create and get Host-Initiated Telemetry Log Data with Windows 10 2004 (from Windows Insider Preview).

Regards,
Ken

**Comment by ken-yossy** [comment] 2020-09-17 06:47
I have created branch named "issue-6".
I will use this branch for this issue.

**Comment by tim-oleksii** [comment] 2020-09-17 08:48
There is one subtle issue with this syscall. Its output applies `little-endianess` on WRD (16 bits).
There is no way to get size of resutling telemetry from the header, as ioctl regenerates it every time by setting `LSP`.

So the only solution - allocating 32 MBs at once (max telemetry size) and reading the whole log page

**Comment by ken-yossy** [comment] 2020-09-20 13:16
merge some commits to this branch from master branch for issue #7

**Comment by ken-yossy** [comment] 2020-10-02 10:05
I just wrote as [1] says and tested with an NVMe SSD with Telemetry support, but got error (error code = 31 "A device attached to the system is not functioning") from `DeviceIoControl()`. There is something wrong in my code.

Note that issuing `Get Log Page` command via `DeviceIoControl()` with `IOCTL_STORAGE_QUERY_PROPERTY` to the same device is succeeded.

```
    GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST request;
    PDEVICE_INTERNAL_STATUS_DATA outBuffer = NULL;
    ULONG outBufferLength = 0;

    // Allocate buffer for use.
    outBufferLength = sizeof(DEVICE_INTERNAL_STATUS_DATA) + 512;
    outBuffer = malloc(outBufferLength);
    if (outBuffer == NULL)
    {
        vPrintSystemError(GetLastError(), "malloc");
        goto error_exit;
    }

    ZeroMemory(&request, sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST));
    ZeroMemory(outBuffer, outBufferLength);

    // from https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ns-ntddstor-get_device_internal_status_data_request
    request.Version = sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST);
    request.Size = sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST);
    request.RequestDataType = DeviceCurrentInternalStatusDataHeader;

    // from https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ns-ntddstor-device_internal_status_data
    outBuffer->Version = sizeof(DEVICE_INTERNAL_STATUS_DATA);
    outBuffer->StatusDataLength = 512;
    outBuffer->Size = outBufferLength + 512;

    // Send request down.
    iResult = iIssueDeviceIoControl(_hDevice,
        IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG,
        &request,
        sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST),
        outBuffer,
        outBufferLength,
        &returnedLength,
        NULL
    );
```
[1] https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddstor/ni-ntddstor-ioctl_storage_get_device_internal_log

**Comment by tim-oleksii** [comment] 2020-10-03 20:56
@ken-yossy  Do you need code sample?

**Comment by ken-yossy** [comment] 2020-10-03 23:24
> @ken-yossy Do you need code sample?

Yes, if you don't mind. I appreciate it.
Now, I'm building Qemu based environment to capture commands and arguments from Windows to SSD.

Ken

**Comment by ken-yossy** [comment] 2020-10-04 09:29
I've built the environment with Windows 10 Insider Preview build 20175, and tested the tool with above code.

The result was that Windows actually issued the Get Log Page command (with Create Telemetry Host-Initiated Data = 1) and the emulated SSD model received it.

I think this result means there's something wrong along response path.

**Comment by tim-oleksii** [comment] 2020-10-05 09:20
This one was checked against our eSSD

``
#include <Windows.h>
#include <iostream>
#include <ntddstor.h>
#include <string>
#include <vector>
#include <sstream>
#include <fstream>

namespace
{
	std::string dev_path = "";
	auto request_data_type = DeviceCurrentInternalStatusDataHeader;
	auto request_data_set = DeviceStatusDataSetUndefined;
	size_t size_to_read = 512;
	std::string output_file_name = "";
};

std::string dt_to_str(DEVICE_INTERNAL_STATUS_DATA_REQUEST_TYPE dt)
{
	switch (dt)
	{
		case DeviceInternalStatusDataRequestTypeUndefined:
			return "DeviceInternalStatusDataRequestTypeUndefined";
		case DeviceCurrentInternalStatusDataHeader:
			return "DeviceCurrentInternalStatusDataHeader";
		case DeviceCurrentInternalStatusData:
			return "DeviceCurrentInternalStatusData";
		default:
			return "Unknown(" + std::to_string(static_cast<unsigned>(dt)) + ")";
	}
}

std::string ds_to_str(DEVICE_INTERNAL_STATUS_DATA_SET ds)
{
	switch (ds)
	{
	case DeviceStatusDataSetUndefined:
		return "DeviceStatusDataSetUndefined";
	case DeviceStatusDataSet1:
		return "DeviceStatusDataSet1";
	case DeviceStatusDataSet2:
		return "DeviceStatusDataSet2";
	case DeviceStatusDataSet3:
		return "DeviceStatusDataSet3";
	case DeviceStatusDataSet4:
		return "DeviceStatusDataSet4";
	case DeviceStatusDataSetMax:
		return "DeviceStatusDataSetMax";
	default:
		return "Unknown(" + std::to_string(static_cast<unsigned>(ds)) + ")";
	}
}

void print_help()
{
	std::cout << 
"Args:\n\
   -d - device path, mandatory.\n\
   -dt - RequestDataType, integer in range [0, 2]\n\
   -ds - RequestDataSet, integer in range [0, 5]\n\
   -s - size to read, default 512\n\
   -o - output file name to store internal log\n\
Example:\n\
   telemetry_read -d  \\\\.\\PhysicalDrive0 -dt 1 -ds 2\n\
   telemetry_read -d  \\\\.\\PhysicalDrive0 -dt 1 -ds 2 -s 4096 -o c:\\tmp\\telemetry.bin";
}

int parse_args(int argc, const char* argv[])
{
	if (argc == 1)
	{
		print_help();
		return -1;
	}

	int arg = 1;
	while (arg < argc)
	{
		if (arg + 1 >= argc)
		{
			std::cout << "Invalid argument count\n\n";
			print_help();
			return -1;
		}

		std::string arg_key = argv[arg];
		std::string arg_value = argv[arg + 1];

		if (arg_key == "-d")
		{
			dev_path = arg_value;
		}
		else if (arg_key == "-dt")
		{
			request_data_type = static_cast<DEVICE_INTERNAL_STATUS_DATA_REQUEST_TYPE>(std::stoi(arg_value));
		}
		else if (arg_key == "-ds")
		{
			request_data_set = static_cast<DEVICE_INTERNAL_STATUS_DATA_SET>(std::stoi(arg_value));
		}
		else if (arg_key == "-s")
		{
			size_to_read = std::stoi(arg_value);
		}
		else if (arg_key == "-o")
		{
			output_file_name = arg_value;
		}

		arg += 2;
	}

	if (dev_path.empty())
	{
		std::cout << "Please provide device path.\n\n";
		print_help();
		return -1;
	}

	return 0;
}

std::string buffer_to_str(const void* buf, size_t size)
{
	std::stringstream ss;
	for (size_t i = 0; i < size; ++i)
	{
		ss << std::hex << static_cast<unsigned>(static_cast<const uint8_t*> (buf)[i]);
	}
	return ss.str();
}

void print_request(const GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST& request)
{
	std::cout << "GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST:\n";
	std::cout << "  .RequestDataType = " << dt_to_str(request.RequestDataType) << "\n";
	std::cout << "  .RequestDataSet = " << ds_to_str(request.RequestDataSet) << "\n";
	std::cout << "  .SizeToRead = " << size_to_read << "\n";
}

void print_status_data(const DEVICE_INTERNAL_STATUS_DATA& data)
{
	std::cout << "DEVICE_INTERNAL_STATUS_DATA:\n";
	std::cout << "  .Version = " << data.Version << "\n";
	std::cout << "  .Size = " << data.Size << "\n";
	std::cout << "  .T10VendorId = " << buffer_to_str(&data.T10VendorId, sizeof(data.T10VendorId)) << "\n";
	std::cout << "  .DataSet1Length = " << data.DataSet1Length << "\n";
	std::cout << "  .DataSet2Length = " << data.DataSet2Length << "\n";
	std::cout << "  .DataSet3Length = " << data.DataSet3Length << "\n";
	std::cout << "  .DataSet4Length = " << data.DataSet4Length << "\n";
	std::cout << "  .StatusDataVersion = " << static_cast<int>(data.StatusDataVersion) << "\n";
	std::cout << "  .ReasonIdentifier = " << buffer_to_str(&data.ReasonIdentifier, sizeof(data.ReasonIdentifier)) << "\n";
	std::cout << "  .StatusDataLength = " << data.StatusDataLength << "\n";

	if (!output_file_name.empty())
	{
		std::ofstream out_file(output_file_name, std::ios::trunc | std::ios::binary | std::ios::out);
		if (!out_file.good())
		{
			std::cout << "Failed to open '" << output_file_name << "' for writing\n";
		}

		out_file.write(reinterpret_cast<const char*>(data.StatusData), data.StatusDataLength);
		std::cout << "Status data saved to file '" << output_file_name << "'\n";
	}
}

std::string GetLastErrorAsString()
{
    //Get the error message, if any.
    DWORD errorMessageID = ::GetLastError();
    if(errorMessageID == 0)
        return std::string(); //No error message has been recorded

    LPSTR messageBuffer = nullptr;
    size_t size = FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
                                 NULL, errorMessageID, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPSTR)&messageBuffer, 0, NULL);

    std::string message(messageBuffer, size);

    //Free the buffer.
    LocalFree(messageBuffer);

    return message;
}

int main(int argc, const char* argv[])
{
	if (auto ret = parse_args(argc, argv) != 0)
	{
		return ret;
	}

	// Open file
	std::cout << "Open file '" << dev_path << "': ";
	HANDLE dev = CreateFileA(dev_path.c_str(),
		GENERIC_READ | GENERIC_WRITE,
		FILE_SHARE_READ | FILE_SHARE_WRITE,
		NULL,
		OPEN_EXISTING,
		FILE_ATTRIBUTE_NORMAL,
		NULL);

	if (dev == INVALID_HANDLE_VALUE)
	{
		std::cout << "Failed\n";
		return -1;
	}
	else
	{
		std::cout << "Succeeded\n";
	}

    // Fill request
	GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST request = {0};
	request.Version = sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST);
	request.Size = sizeof(GET_DEVICE_INTERNAL_STATUS_DATA_REQUEST);
	request.RequestDataType = DeviceCurrentInternalStatusDataHeader;


	const size_t out_buf_size = FIELD_OFFSET(DEVICE_INTERNAL_STATUS_DATA, StatusData) + size_to_read;

	std::vector<uint8_t> out_buffer(out_buf_size);

	DWORD bytes_returned = 0;

	print_request(request);

	// Read internal log
	std::cout << "DeviceIoControl(IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG): ";
	auto ioctl_result = DeviceIoControl(dev, IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG, &request, sizeof(request), &out_buffer.front(), out_buffer.size(), &bytes_returned, nullptr);

    request.RequestDataType = DeviceCurrentInternalStatusData;
    request.RequestDataSet = DeviceStatusDataSet1;

     DeviceIoControl(dev,
                             IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG,
                             &request,
                             sizeof(request),
                     &out_buffer.front(), out_buffer.size(), &bytes_returned, nullptr);


    if (ioctl_result == 0)
	{
		auto last_error = GetLastErrorAsString();
		std::cout << "Failed\n";
		std::cout << "Error: " << last_error << "\n" ;
		return -1;
	}
	else
	{
		std::cout << "Succeeded\n";
	}

	CloseHandle(dev);

	std::cout << "BytesReturned = " << bytes_returned << "\n";
	print_status_data(*reinterpret_cast<DEVICE_INTERNAL_STATUS_DATA*>( & out_buffer.front()));

	return 0;
}
``

**Comment by tim-oleksii** [comment] 2020-10-05 09:23
@ken-yossy you may find snippet here
https://pastebin.pl/view/416a9efb

**Comment by ken-yossy** [comment] 2020-10-06 00:33
@tim-oleksii 
Thank you very much for your sample.
With it, I have succeeded in DeviceIoControl().
I finally understood your comments in this ticket about the data layout (NVMe spec and DEVICE_INTERNAL_STATUS_DATA) and endianess...

Currently, I've not understood why it works and the data (DEVICE_INTERNAL_STATUS_DATA) received from (emulated) SSD does not seem as I expects.

I will do some tries to resolve them.

Ken

**Comment by tim-oleksii** [comment] 2020-10-06 10:04
@ken-yossy  sorry, I can't help with QEMU. eSSD was used to grab telemetry data. Actually, this is the first time I hear about SSD emulation. Are there any insights how to do it?

**Comment by ken-yossy** [comment] 2020-10-07 04:38
@tim-oleksii don't worry. This is a matter regarding to the way I select.

> Actually, this is the first time I hear about SSD emulation. Are there any insights how to do it?

Qemu has emulation codes of NVMe storage(s) and can provide emulated NVMe storage to guest OSes. So, I install Windows 10 Insider Preview as a guest OS on qemu, edit the emulation codes, expose it to the Windows, and test this tool with changing storage's behavior.

I think it's almost the same as your way; the difference is that you are using real SSD and changing real FW.

One thing that I have found along this way is that installing recent Windows 10 (including Insider Preview) as a guest OS on qemu is very difficult. I encountered errors many times and restarted installation from the beginning each time...so, I strongly recommend using real devices if possible :-)

I will push edited codes of this tool and summarize the behavior of Windows as far as I understood along this trial and error.

Thank you,
Ken

**Comment by ken-yossy** [comment] 2020-10-07 10:22
I created [wiki page](https://github.com/ken-yossy/nvmetool-win/wiki/Getting-telemetry-data-with-IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG) for this topic and wrote observations from the results of experiments. I'm sorry for rough description...

**Comment by ken-yossy** [comment] 2020-10-08 02:06
I've merged the changes made in the branch "issue-6" into main (master) branch.

**Comment by ken-yossy** [comment] 2020-10-16 13:21
Along this ticket, it is confirmed that we can create Host-Initiated Telemetry (by setting "Create Telemetry Host-Initiated Data" bit) and retrieve the telemetry header with IOCTL_STORAGE_GET_DEVICE_INTERNAL_LOG using Windows' inbox NVMe device driver.

But, the NVMe spec says the content of Telemetry data is vendor specific, and I don't know  real SSDs that create and export Telemetry data.

So I would like to close this ticket a week later.

If I find such SSDs and any issue in this tool,  I will open a new issue at that time.

Thank you,
Ken

**Closed as completed** 2020-10-24 00:07 UTC
Labels: bug, enhancement
